use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
distmeta
dists
dir
mailto
metacpan
releaser
subkey
subkeys
David
Golden
dagolden
Ricardo
Signes
rjbs
and
Ansgar
Burchardt
ansgar
Avar
Arnfjord
Bjarmason
avar
Christopher
Madsen
cjm
Chuck
Adams
cja987
Cory
Watson
gphat
Damyan
Ivanov
dam
Eric
Wilhelm
ewilhelm
Graham
Knop
haarg
Gregor
Hermann
gregoa
Karen
Etheridge
ether
Kenichi
Ishigaki
ishigaki
Ken
Williams
kwilliams
Lars
Dieckow
daxim
Leon
Timmermans
leont
majensen
maj
Mark
Fowler
markf
Matt
Trout
mst
Michael
Schwern
mschwern
moznion
Olaf
Alders
olaf
Olivier
Mengue
dolmen
Randy
Sims
randys
lib
CPAN
Meta
History
Meta_1_0
Spec
Meta_1_1
Meta_1_4
Prereqs
Meta_1_2
Feature
Merge
Validator
Meta_1_3
Converter
