---
abstract: 'Perl binding for Redis database'
author:
  - 'Pedro Melo <melo@cpan.org>'
  - 'Damien Krotkine <dams@cpan.org>'
build_requires:
  Digest::SHA: 0
  File::Spec: 0
  IO::Handle: 0
  IO::String: 0
  IPC::Cmd: 0
  IPC::Open3: 0
  Pod::Coverage::TrustPod: 0
  Test::CPAN::Meta: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.98
  Test::SharedFork: 0
  Test::TCP: 1.19
configure_requires:
  ExtUtils::MakeMaker: 6.63_03
  Module::Build::Tiny: 0.036
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis
requires:
  IO::Socket::Timeout: 0.22
  Try::Tiny: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/PerlRedis/perl-redis/issues
  homepage: https://github.com/PerlRedis/perl-redis
  repository: https://github.com/PerlRedis/perl-redis.git
version: 1.976
