---
abstract: 'a PerlIO layer that adds read & write timeout to a handle'
author:
  - "Damien \"dams\" Krotkine"
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-via-Timeout
provides:
  PerlIO::via::Timeout:
    file: lib/PerlIO/via/Timeout.pm
    version: 0.29
requires:
  Exporter: 5.57
  PerlIO::via: 0
  Scalar::Util: 0
  Time::Out: 0
resources:
  repository: git://github.com/dams/perlio-via-timeout.git
version: 0.29
